matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "8"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - node_modules

before_cache:
  - brew cleanup

before_install:
  - brew update

install:
  - yarn
  # - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/9a70413d137839de0054571e5f85fd07ee400955/Formula/qt.rb
  - brew install qt5
  - brew link --force qt

before_script:
  - yarn build
  - export QMAKESPEC=macx-clang
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - qmake -v
  - qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=release "$TRAVIS_BUILD_DIR/native"

script:
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 all
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 check
  # - '[ "$TRAVIS_OS_NAME" != osx ] || make -C "$TRAVIS_BUILD_DIR-build/pkg/osx" dmg'
