language: cpp

os:
  - linux
  - osx

dist: xenial

compiler:
  - clang
  - gcc

env:
  - QT=5
  # Tip: curl -s 'https://api.launchpad.net/1.0/~beineri/ppas?ws.size=200' | jq -r '"beineri/" + .entries[].name' | sed -nEe 's/.*opt-qt(([0-9]{2})[0-9]?|-([0-9])+\.([0-9]+)\.([0-9]+))-xenial/  - QT=\2\3\4 BREW=EX PPA=&/p'
  - QT=56 PPA=beineri/opt-qt562-xenial
  - QT=56 PPA=beineri/opt-qt563-xenial
  - QT=57 PPA=beineri/opt-qt571-xenial
  - QT=58 PPA=beineri/opt-qt58-xenial
  - QT=59 PPA=beineri/opt-qt59-xenial
  - QT=59 PPA=beineri/opt-qt591-xenial
  - QT=59 PPA=beineri/opt-qt592-xenial
  - QT=59 PPA=beineri/opt-qt593-xenial
  - QT=59 PPA=beineri/opt-qt594-xenial
  - QT=59 PPA=beineri/opt-qt595-xenial
  - QT=59 PPA=beineri/opt-qt596-xenial
  - QT=510 PPA=beineri/opt-qt-5.10.0-xenial
  - QT=510 PPA=beineri/opt-qt-5.10.1-xenial
  - QT=511 PPA=beineri/opt-qt-5.11.0-xenial
  - QT=511 PPA=beineri/opt-qt-5.11.1-xenial
  - QT=511 PPA=beineri/opt-qt-5.11.2-xenial

matrix:
  # Qt no longer supports GCC on OSX.
  allow_failures:
    - { os: osx, compiler: gcc, env: QT=5 }
  exclude:
    # Tip: curl -s 'https://api.launchpad.net/1.0/~beineri/ppas?ws.size=200' | jq -r '"beineri/" + .entries[].name' | sed -nEe 's/.*opt-qt(([0-9]{2})[0-9]?|-([0-9])+\.([0-9]+)\.([0-9]+))-xenial/    - { os: osx, env: QT=\2\3\4 PPA=& }/p'
    - { os: osx, env: QT=56 PPA=beineri/opt-qt562-xenial }
    - { os: osx, env: QT=56 PPA=beineri/opt-qt563-xenial }
    - { os: osx, env: QT=57 PPA=beineri/opt-qt571-xenial }
    - { os: osx, env: QT=58 PPA=beineri/opt-qt58-xenial }
    - { os: osx, env: QT=59 PPA=beineri/opt-qt59-xenial }
    - { os: osx, env: QT=59 PPA=beineri/opt-qt591-xenial }
    - { os: osx, env: QT=59 PPA=beineri/opt-qt592-xenial }
    - { os: osx, env: QT=59 PPA=beineri/opt-qt593-xenial }
    - { os: osx, env: QT=59 PPA=beineri/opt-qt594-xenial }
    - { os: osx, env: QT=59 PPA=beineri/opt-qt595-xenial }
    - { os: osx, env: QT=59 PPA=beineri/opt-qt596-xenial }
    - { os: osx, env: QT=510 PPA=beineri/opt-qt-5.10.0-xenial }
    - { os: osx, env: QT=510 PPA=beineri/opt-qt-5.10.1-xenial }
    - { os: osx, env: QT=511 PPA=beineri/opt-qt-5.11.0-xenial }
    - { os: osx, env: QT=511 PPA=beineri/opt-qt-5.11.1-xenial }
    - { os: osx, env: QT=511 PPA=beineri/opt-qt-5.11.2-xenial }

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
# - '[ "$TRAVIS_OS_NAME" != osx ] || brew search qt' # Causes Homebrew API rate-limit issues.

install:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns libgl1-mesa-dev'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt'

before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - qmake -v
  - qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=release "$TRAVIS_BUILD_DIR"

script:
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 all
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 check
  - '[ "$TRAVIS_OS_NAME" != osx ] || make -C "$TRAVIS_BUILD_DIR-build/pkg/osx" dmg'
